### ISSUE TITLE
Does not work for an app started with electron-forge on OSX

### ISSUE THREAD

**Issue by deepak** [jviotti/electron-is-running-in-asar#1]
if i start a packaged app on OSX `process.mainModule.filename` is:

> /Users/deepak/Code/mine/electron-and-react/electron-webview-todo/out/electron-webview-todo-mas-x64/electron-webview-todo.app/Contents/Resources/app/src/static/index.html

but when i start the app using "npm start" it is:

> /Users/deepak/Code/mine/electron-and-react/electron-webview-todo/src/static/index.html

I think we an check if there is a <something>.app in the pathname

what do you think ?

**Comment by jviotti** [comment]
Hi @deepak ,

This module is concerned with determining if the application is being loaded from an `asar` archive (see https://github.com/electron/asar). As far as I can see in your filename path, you're not running this inside an `asar`, but directly inside the `Contents/Resources/app` directory, so the `false` result from this module is expected.
